### ISSUE TITLE
HOPPER_MINECART error

### ISSUE THREAD

**Issue by myavuzokumus** [Guillaume-Lebegue/IslandUpgrades#10]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/86210426-461f8b80-bb7d-11ea-8374-0ce8101fa9bf.png)

```
entity-limits-upgrade:
  HOPPER_MINECART:
    tier1:
      max-level: 2
      upgrade: "5"
      island-min-level: "100"
      vault-cost: "[numberPlayer]*[islandLevel]*[level]*50"
    tier2:
      max-level: 3
      upgrade: "8"
      island-min-level: "1000"
      vault-cost: "[numberPlayer]*[islandLevel]*[level]*50"
    tier3:
      max-level: 4
      upgrade: "13"
      island-min-level: "5000"
      vault-cost: "[numberPlayer]*[islandLevel]*[level]*50"
    tier4:
      max-level: 5
      upgrade: "20"
      island-min-level: "10000"
      vault-cost: "[numberPlayer]*[islandLevel]*[level]*50"

entity-icon:
  HOPPER_MINECART: HOPPER_MINECART
```

##### Output of `/bbox version` (Mandatory)

![image](https://user-images.githubusercontent.com/47111280/86210452-53d51100-bb7d-11ea-8969-f81f8327776a.png)
