### ISSUE TITLE
More freedom with name/description

### ISSUE THREAD

**Issue by CodfishBender** [Guillaume-Lebegue/IslandUpgrades#34]
Hi there,

I propose a few of edits which will vastly improve this plugins visual capabilities.

Firstly, please allow the ability to make [block] lower case. E.g. "Chicken Limit" instead of "CHICKEN Limit".

Additionally, please allow a single description field for each upgrade type which takes all placeholders.
This way the descriptions can multi-line and customized to anything:
```ui:
    upgradepanel:
      entity-limit-desc: |
        &a[block] Limit
        &r
        &7Increases the maximum number of
        &6[block] &7on your island.
        &r
        &7Requirements:
        &7Money: &a$[cost]
        &7Island Level: &b[islandlevel]
        &r
        &7Refresh island level with /is level
```
Behold, a single entry with endless customization.

And finally, please allow the ability to show the current and next limit amount. I.e. The amount of chickens allowed the the current level and also the next level. This allows for a description like:
`Upgrade limit: [current] >> [next]`

Edit:
It would also be nice if prices were formatted. Currently [cost] will return $1000000, where $1,000,000 would be much easier to read.

**Comment by Guillaume-Lebegue** [comment]
Hello, for the description and name, I'm currently working on refactoring how upgrades are made.
I'm doing an admin interface (like the challanges addon) that can customize a lot more things.

As for the placeholders in the description and the price format, that's a good idea.

- [ ] Placeholders description: [current] [next]
- [ ] Cost format

If you have any idea for other placeholders or enhancement, don't hesitate to tell them.

**Comment by CodfishBender** [comment]
Thanks for the response, it's really good to hear things are being improved. 
I'd like to give one more suggestion in regards to the item description: The ability to create individual descriptions for each tier.
```
    command-upgrade:
      lambda-upgrade:
        tier2:
          max-level: 2
          island-min-level: "2"
          vault-cost: "[level]*200"
          console: true
          command:
            - "say [player] has upgrade his lambda to level [level]"
            - "say [player] has attained max on BSkyBlock"
          custom-desc: "Description goes here etc.."
```
In this case the custom-desc would override the locale. If custom-desc is not present or null, it would read from the locale instead. 

This allows for completely unique upgrades or tiers alongside the generic upgrades, such as a one-time purchase to summon an end portal, or to activate another feature. Point being, it would be unique from the rest.
