### ISSUE TITLE
wrong tier order in GUI

### ISSUE THREAD

**Issue by QuestionCatcher** [Guillaume-Lebegue/IslandUpgrades#51]
### Expected behavior

in config file i have tier order:
Tier1
Tier2
Tier3
Tier4

For every single upgrade i have on server

### Observed/Actual behavior

under /is upgrade command in GUI some items starts their upgrade from Tier3 or Tier4 

### Steps/models to reproduce

1. Add upgrades and tiers
2. Restart sever
3. Run /is upgrade

### BentoBox version

[16:28:20] [Server thread/INFO]: Running PAPER 1.20.1.
[16:28:20] [Server thread/INFO]: BentoBox version: 1.24.1
[16:28:20] [Server thread/INFO]: Database: JSON
[16:28:20] [Server thread/INFO]: Loaded Game Worlds:
[16:28:20] [Server thread/INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[16:28:20] [Server thread/INFO]: Loaded Addons:
[16:28:20] [Server thread/INFO]: Bank 1.7.0 (ENABLED)
[16:28:20] [Server thread/INFO]: Biomes 2.1.1 (ENABLED)
[16:28:20] [Server thread/INFO]: Border 4.1.1 (ENABLED)
[16:28:20] [Server thread/INFO]: BSkyBlock 1.16.1 (ENABLED)
[16:28:20] [Server thread/INFO]: Chat 1.1.4 (ENABLED)
[16:28:20] [Server thread/INFO]: ControlPanel 1.13.0 (ENABLED)
[16:28:20] [Server thread/INFO]: ExtraMobs 1.12 (ENABLED)
[16:28:20] [Server thread/INFO]: IslandFly 1.11.0 (ENABLED)
[16:28:20] [Server thread/INFO]: Level 2.11.0 (ENABLED)
[16:28:20] [Server thread/INFO]: Likes 2.3.1 (ENABLED)
[16:28:20] [Server thread/INFO]: Limits 1.19.1 (ENABLED)
[16:28:20] [Server thread/INFO]: MagicCobblestoneGenerator 2.5.1 (ENABLED)
[16:28:20] [Server thread/INFO]: Upgrades 0.3.0-SNAPSHOT-b130 (ENABLED)
[16:28:20] [Server thread/INFO]: Visit 1.6.0 (ENABLED)
[16:28:20] [Server thread/INFO]: Warps 1.13.0 (ENABLED)

### Plugin list

[16:28:36] [Server thread/INFO]: Server Plugins (53):
[16:28:36] [Server thread/INFO]: Paper Plugins:
[16:28:36] [Server thread/INFO]:  - MarriageMaster, Minepacks
[16:28:36] [Server thread/INFO]: Bukkit Plugins:
[16:28:36] [Server thread/INFO]:  - BanAnnouncer, BentoBox, BentoBox-Bank, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-IslandFly, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-MagicCobblestoneGenerator
[16:28:36] [Server thread/INFO]:  BentoBox-Visit, BentoBox-Warps, Citizens, CMI, CMILib, CoreProtect, DailyRewardsPlus, DeluxeMenus, EasyCommandBlocker, ExcellentCrates
[16:28:36] [Server thread/INFO]:  ezAuctions, EzChestShop, FastAsyncWorldEdit, FlareTokens, HeadDatabase, InventoryRollbackPlus, ItemEdit, Jobs, LiteBans, LotterySix
[16:28:36] [Server thread/INFO]:  LPX, LuckPerms, NexEngine, PlaceholderAPI, ProtocolLib, Quests, ServerBackup, ShopGUIPlus, SpawnerMeta, Spicord
[16:28:36] [Server thread/INFO]:  *T-Vouchers, TAB, Vault, ViaVersion, VoidSpawn, VotifierPlus, VotingPlugin, Vulcan, WorldGuard, WorldGuardExtraFlags
[16:28:36] [Server thread/INFO]:  zAuctionHouseV3

### Other
Tiers on fresh created island
Wrong order:
![wrong_order](https://github.com/BentoBoxWorld/Upgrades/assets/73604198/702e9a26-8fce-4c9d-932e-800c8dddc35a)
Config for Creeper upgrade with wrong tier order:
```
  CREEPER:
   tier1:
     max-level: 5
     upgrade: "3"
     island-min-level: "250"
     vault-cost: "10000"
   tier2:
     max-level: 5
     upgrade: "5"
     island-min-level: "1000"
     vault-cost: "[level]*2000"
   tier3:
     max-level: 5
     upgrade: "7"
     island-min-level: "2500"
     vault-cost: "[level]*2500"
   tier4:
     max-level: 5
     upgrade: "10"
     island-min-level: "5000"
     vault-cost: "[level]*10000"
``` 
     
Correct order:
![corretc_order](https://github.com/BentoBoxWorld/Upgrades/assets/73604198/346fdd7f-c602-45b2-8bc5-a650cbc1fd97)

Config for Cactus upgrade with correct tier order: 
```
  CACTUS:
   tier1:
     max-level: 3
     upgrade: "5"
     island-min-level: "250"
     vault-cost: "10000"
   tier2:
     max-level: 5
     upgrade: "5"
     island-min-level: "1000"
     vault-cost: "[level]*2000"
   tier3:
     max-level: 6
     upgrade: "7"
     island-min-level: "2500"
     vault-cost: "[level]*2500"
   tier4:
     max-level: 4
     upgrade: "10"
     island-min-level: "5000"
     vault-cost: "[level]*7500"
```
